CREATE SEQUENCE family_seq START WITH 0;

CREATE TABLE PERSON (
  ID INTEGER not null primary key,
  VERSION INTEGER,
  GENDER VARCHAR(8) not null,
  NAME VARCHAR(32) not null
);

CREATE index PERSON_NAME on PERSON (NAME);
CREATE unique index unique_person_name on PERSON (NAME);

CREATE table FAMILY_MEMBER (
	ID INTEGER not null primary key,
	FATHER_ID INTEGER,
	MOTHER_ID INTEGER,
	SPOUSE_ID INTEGER,
	FOREIGN KEY (ID) REFERENCES PERSON(id),
	FOREIGN KEY (FATHER_ID) REFERENCES FAMILY_MEMBER(id),
	FOREIGN KEY (MOTHER_ID) REFERENCES FAMILY_MEMBER(id),
	FOREIGN KEY (SPOUSE_ID) REFERENCES FAMILY_MEMBER(id)
);

CREATE SEQUENCE event_seq START WITH 0;

CREATE TABLE EVENT_LOG (
	SEQUENCE INTEGER not null primary key,
	TYPE VARCHAR(64) not null,
	DATA VARCHAR(512) not null
);



